<?php echo $this->doctype(); ?>

<html lang="en">
  <head>

    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
  </head>

  <body>

      <?php echo $this->content; ?>

  </body>
</html>